<?php

namespace ContainerIwAkOJC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSearch_EventListener_HitService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_search.event_listener.hit' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Search\EventListener\HitListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Search/EventListener/HitListener.php';

        return $container->privates['sulu_search.event_listener.hit'] = new \Sulu\Bundle\PageBundle\Search\EventListener\HitListener(($container->services['sulu_core.webspace.request_analyzer'] ?? $container->getSuluCore_Webspace_RequestAnalyzerService()));
    }
}
