<?php

namespace ContainerIwAkOJC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_TextEditorService extends App_KernelProdContainer
{
    /*
     * Gets the public 'sulu.content.type.text_editor' shared service.
     *
     * @return \Sulu\Component\Content\Types\TextEditor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Content/ContentTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Content/ContentTypeExportInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Content/SimpleContentType.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Content/Types/TextEditor.php';

        return $container->services['sulu.content.type.text_editor'] = new \Sulu\Component\Content\Types\TextEditor(($container->privates['sulu_markup.parser'] ?? $container->getSuluMarkup_ParserService()));
    }
}
