<?php

namespace ContainerIwAkOJC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluHash_EventSubscriber_SerializerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_hash.event_subscriber.serializer' shared service.
     *
     * @return \Sulu\Component\Hash\Serializer\Subscriber\HashSerializeEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/EventDispatcher/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Hash/Serializer/Subscriber/HashSerializeEventSubscriber.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Hash/HasherInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Hash/AuditableHasher.php';

        return $container->privates['sulu_hash.event_subscriber.serializer'] = new \Sulu\Component\Hash\Serializer\Subscriber\HashSerializeEventSubscriber(($container->privates['sulu_hash.auditable_hasher'] ?? ($container->privates['sulu_hash.auditable_hasher'] = new \Sulu\Component\Hash\AuditableHasher())));
    }
}
