<?php

namespace ContainerIwAkOJC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_RepresentationHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_core.representation_handler' shared service.
     *
     * @return \Sulu\Component\Serializer\RepresentationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/EventDispatcher/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Serializer/RepresentationSubscriber.php';

        return $container->privates['sulu_core.representation_handler'] = new \Sulu\Component\Serializer\RepresentationSubscriber();
    }
}
