<?php

namespace ContainerIwAkOJC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_FieldMetadataValidator_ChainService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_admin.field_metadata_validator.chain' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\ChainFieldMetadataValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Validation/FieldMetadataValidatorInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Validation/ChainFieldMetadataValidator.php';

        return $container->privates['sulu_admin.field_metadata_validator.chain'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\ChainFieldMetadataValidator(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_admin.field_metadata_validator.types_property'] ?? ($container->privates['sulu_admin.field_metadata_validator.types_property'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\TypesPropertyFieldMetadataValidator()));
            yield 1 => ($container->privates['sulu_admin.field_metadata_validator.block'] ?? ($container->privates['sulu_admin.field_metadata_validator.block'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Validation\BlockFieldMetadataValidator()));
            yield 2 => ($container->privates['sulu_media.field_metadata_validator.image_map'] ?? ($container->privates['sulu_media.field_metadata_validator.image_map'] = new \Sulu\Bundle\MediaBundle\Metadata\ImageMapFieldMetadataValidator()));
        }, 3));
    }
}
