<?php

namespace ContainerRqrmNio;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Voter_Sulu_Preview_VoterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.voter.sulu.preview.voter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/Security/PreviewVoter.php';

        return $container->privates['debug.security.voter.sulu.preview.voter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \Sulu\Bundle\PreviewBundle\Infrastructure\Symfony\Security\PreviewVoter(), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
