<?php

namespace ContainerRqrmNio;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveBuild_Command_BuildService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_build.command.build' shared service.
     *
     * @return \Sulu\Bundle\CoreBundle\CommandOptional\SuluBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/build-bundle/Command/BuildCommand.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/CommandOptional/SuluBuildCommand.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/build-bundle/Build/BuildRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/build-bundle/Build/BuilderInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/SuluBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/DatabaseBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/PhpcrBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/PhpcrMigrationsBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/FixturesBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SearchBundle/Build/IndexBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Media/SystemCollections/SystemCollectionBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Build/UserBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Build/SecurityBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Build/NodeOrderBuilder.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/build-bundle/Builder/VirtualBuilder.php';

        $a = new \Massive\Bundle\BuildBundle\Build\BuildRegistry();
        $a->addBuilder(new \Sulu\Bundle\CoreBundle\Build\DatabaseBuilder());
        $a->addBuilder(new \Sulu\Bundle\CoreBundle\Build\PhpcrBuilder());
        $a->addBuilder(new \Sulu\Bundle\CoreBundle\Build\PhpcrMigrationsBuilder(($container->privates['phpcr_migrations.migrator_factory'] ?? $container->load('getPhpcrMigrations_MigratorFactoryService')), ($container->privates['phpcr_migrations.version_storage'] ?? $container->load('getPhpcrMigrations_VersionStorageService'))));
        $a->addBuilder(new \Sulu\Bundle\CoreBundle\Build\FixturesBuilder());
        $a->addBuilder(new \Sulu\Bundle\SearchBundle\Build\IndexBuilder());
        $a->addBuilder(new \Sulu\Component\Media\SystemCollections\SystemCollectionBuilder(($container->services['sulu_media.system_collections.manager'] ?? $container->load('getSuluMedia_SystemCollections_ManagerService'))));
        $a->addBuilder(new \Sulu\Bundle\SecurityBundle\Build\UserBuilder());
        $a->addBuilder(new \Sulu\Bundle\SecurityBundle\Build\SecurityBuilder());
        $a->addBuilder(new \Sulu\Bundle\PageBundle\Build\NodeOrderBuilder(($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), ($container->services['doctrine_phpcr.session'] ?? $container->getDoctrinePhpcr_SessionService()), ($container->services['sulu_document_manager.live_session'] ?? $container->getSuluDocumentManager_LiveSessionService()), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), ($container->services['sulu_document_manager.property_encoder'] ?? $container->getSuluDocumentManager_PropertyEncoderService())));
        $a->addBuilder(new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('prod', [0 => 'database', 1 => 'phpcr', 2 => 'fixtures', 3 => 'phpcr_migrations', 4 => 'system_collections', 5 => 'security']));
        $a->addBuilder(new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('dev', [0 => 'database', 1 => 'fixtures', 2 => 'phpcr', 3 => 'user', 4 => 'phpcr_migrations', 5 => 'system_collections', 6 => 'security']));
        $a->addBuilder(new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('maintain', [0 => 'node_order', 1 => 'search_index', 2 => 'phpcr_migrations']));

        $container->privates['massive_build.command.build'] = $instance = new \Sulu\Bundle\CoreBundle\CommandOptional\SuluBuildCommand($a, $container);

        $instance->setName('sulu:build');

        return $instance;
    }
}
