<?php

namespace ContainerRqrmNio;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_AccountManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_contact.account_manager' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Contact\AccountManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Contact/AccountFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Contact/AccountFactory.php';

        return $container->services['sulu_contact.account_manager'] = new \Sulu\Bundle\ContactBundle\Contact\AccountManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['sulu_tag.tag_manager'] ?? $container->getSuluTag_TagManagerService()), ($container->services['sulu_media.media_manager'] ?? $container->getSuluMedia_MediaManagerService()), ($container->services['sulu_contact.account_factory'] ?? ($container->services['sulu_contact.account_factory'] = new \Sulu\Bundle\ContactBundle\Contact\AccountFactory('Sulu\\Bundle\\ContactBundle\\Entity\\Account'))), ($container->services['sulu.repository.account'] ?? $container->getSulu_Repository_AccountService()), ($container->services['sulu.repository.contact'] ?? $container->getSulu_Repository_ContactService()), ($container->services['sulu.repository.media'] ?? $container->getSulu_Repository_MediaService()), ($container->privates['sulu_activity.domain_event_collector'] ?? $container->getSuluActivity_DomainEventCollectorService()), 'Sulu\\Bundle\\ContactBundle\\Entity\\Account');
    }
}
