<?php

namespace ContainerRqrmNio;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Phpcr_RefreshService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.phpcr.refresh' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Phpcr\RefreshSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/DocumentManager/Subscriber/Phpcr/RefreshSubscriber.php';

        return $container->privates['sulu_document_manager.subscriber.phpcr.refresh'] = new \Sulu\Component\DocumentManager\Subscriber\Phpcr\RefreshSubscriber(($container->privates['sulu_document_manager.event_dispatcher.standard'] ?? $container->getSuluDocumentManager_EventDispatcher_StandardService()), ($container->privates['sulu_document_manager.document_registry'] ?? ($container->privates['sulu_document_manager.document_registry'] = new \Sulu\Component\DocumentManager\DocumentRegistry('en'))));
    }
}
