<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDtlContent_Form_Factory_DocumentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'dtl_content.form.factory.document_type' shared service.
     *
     * @return \Sulu\Component\Content\Form\Type\DocumentObjectType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Content/Form/Type/DocumentObjectType.php';

        return $container->privates['dtl_content.form.factory.document_type'] = new \Sulu\Component\Content\Form\Type\DocumentObjectType(($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()));
    }
}
