<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_phpcr.jackalope_doctrine_dbal.schema' shared service.
     *
     * @return \Jackalope\Transport\DoctrineDBAL\RepositorySchema
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema'] = $container->createProxy('RepositorySchema_fb41d27', function () use ($container) {
                return \RepositorySchema_fb41d27::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 5).'/vendor/doctrine/dbal/src/Schema/AbstractAsset.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/dbal/src/Schema/Schema.php';
        include_once \dirname(__DIR__, 5).'/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/RepositorySchema.php';

        return new \Jackalope\Transport\DoctrineDBAL\RepositorySchema([], ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));
    }
}
