<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_Search_EventSubscriber_DoctrineOrmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_search.search.event_subscriber.doctrine_orm' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\EventSubscriber\DoctrineOrmSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/EventSubscriber/DoctrineOrmSubscriber.php';

        return $container->privates['massive_search.search.event_subscriber.doctrine_orm'] = new \Massive\Bundle\SearchBundle\Search\EventSubscriber\DoctrineOrmSubscriber(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
