<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_PublicPreviewControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_preview.public_preview_controller' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\UserInterface\Controller\PublicPreviewController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PublicPreviewController.php';

        return $container->services['sulu_preview.public_preview_controller'] = new \Sulu\Bundle\PreviewBundle\UserInterface\Controller\PublicPreviewController(($container->privates['sulu_preview.preview.renderer'] ?? $container->load('getSuluPreview_Preview_RendererService')), ($container->privates['sulu_preview.preview_object_provider_registry'] ?? $container->load('getSuluPreview_PreviewObjectProviderRegistryService')), ($container->privates['sulu_preview.preview_link_repository'] ?? $container->load('getSuluPreview_PreviewLinkRepositoryService')), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['.container.private.profiler'] ?? $container->get_Container_Private_ProfilerService()));
    }
}
