<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Repository_AccountService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.repository.account' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Entity\AccountRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->services['sulu.repository.account'] = $container->createProxy('AccountRepository_21f7ad1', function () use ($container) {
                return \AccountRepository_21f7ad1::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Persistence/Repository/RepositoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Entity/AccountRepositoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/persistence/src/Persistence/Mapping/ClassMetadata.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadata.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        return new \Sulu\Bundle\ContactBundle\Entity\AccountRepository($a, $a->getClassMetadata('Sulu\\Bundle\\ContactBundle\\Entity\\Account'));
    }
}
