<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Teaser_ProviderPoolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.teaser.provider_pool' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Teaser\Provider\TeaserProviderPool
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Teaser/Provider/TeaserProviderPoolInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Teaser/Provider/TeaserProviderPool.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Teaser/Provider/TeaserProviderInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Teaser/PageTeaserProvider.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Teaser/PHPCRPageTeaserProvider.php';

        $a = ($container->services['translator'] ?? $container->getTranslatorService());

        return $container->privates['sulu_page.teaser.provider_pool'] = new \Sulu\Bundle\PageBundle\Teaser\Provider\TeaserProviderPool(['pages' => new \Sulu\Bundle\PageBundle\Teaser\PageTeaserProvider(($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService')), $a, true, new \Sulu\Bundle\PageBundle\Teaser\PHPCRPageTeaserProvider(($container->privates['sulu.content.query_executor'] ?? $container->getSulu_Content_QueryExecutorService()), ($container->privates['sulu_page.smart_content.data_provider.content.query_builder'] ?? $container->load('getSuluPage_SmartContent_DataProvider_Content_QueryBuilderService')), ($container->services['sulu_page.structure.factory'] ?? $container->getSuluPage_Structure_FactoryService()), $a, true, $container->parameters['sulu_security.permissions']))]);
    }
}
