<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_AdminPoolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_admin.admin_pool' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Admin\AdminPool
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Admin/AdminPool.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Admin/View/ViewProviderInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationProviderInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Admin/Admin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SearchBundle/Admin/SearchAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Admin/View/ViewBuilderFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Admin/View/ViewBuilderFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ActivityBundle/Infrastructure/Sulu/Admin/View/ActivityViewBuilderFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ActivityBundle/Infrastructure/Sulu/Admin/View/ActivityViewBuilderFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Admin/WebsiteAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CustomUrlBundle/Admin/CustomUrlAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Admin/PreviewAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ActivityBundle/Infrastructure/Sulu/Admin/ActivityAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/TrashBundle/Infrastructure/Sulu/Admin/TrashAdmin.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php';

        $container->services['sulu_admin.admin_pool'] = $instance = new \Sulu\Bundle\AdminBundle\Admin\AdminPool();

        $a = new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory();
        $b = ($container->services['sulu_security.security_checker'] ?? $container->getSuluSecurity_SecurityCheckerService());
        $c = ($container->services['sulu.core.localization_manager'] ?? $container->load('getSulu_Core_LocalizationManagerService'));
        $d = ($container->services['router'] ?? $container->getRouterService());
        $e = ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService());
        $f = new \Sulu\Bundle\ActivityBundle\Infrastructure\Sulu\Admin\View\ActivityViewBuilderFactory($a, $b);

        $instance->addAdmin(new \Sulu\Bundle\SearchBundle\Admin\SearchAdmin($a));
        $instance->addAdmin(new \Sulu\Bundle\ContactBundle\Admin\ContactAdmin($a, $b, ($container->services['doctrine'] ?? $container->getDoctrineService())));
        $instance->addAdmin(new \Sulu\Bundle\MediaBundle\Admin\MediaAdmin($a, $b, $c, $d, $e, $f));
        $instance->addAdmin(new \Sulu\Bundle\CategoryBundle\Admin\CategoryAdmin($a, $b, $c));
        $instance->addAdmin(new \Sulu\Bundle\SnippetBundle\Admin\SnippetAdmin($a, $b, $e, true));
        $instance->addAdmin(new \Sulu\Bundle\PageBundle\Admin\PageAdmin($a, $e, $b, ($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), ($container->privates['sulu_page.teaser.provider_pool'] ?? $container->load('getSuluPage_Teaser_ProviderPoolService')), false, $f));
        $instance->addAdmin(new \Sulu\Bundle\TagBundle\Admin\TagAdmin($a, $b));
        $instance->addAdmin(new \Sulu\Bundle\WebsiteBundle\Admin\WebsiteAdmin($a, $e, $b, $d));
        $instance->addAdmin(new \Sulu\Bundle\CustomUrlBundle\Admin\CustomUrlAdmin($e, $a, $b));
        $instance->addAdmin(new \Sulu\Bundle\PreviewBundle\Admin\PreviewAdmin($d, 500, 'auto', $container->parameters['kernel.bundles']));
        $instance->addAdmin(new \Sulu\Bundle\ActivityBundle\Infrastructure\Sulu\Admin\ActivityAdmin($a, $b));
        $instance->addAdmin(new \Sulu\Bundle\TrashBundle\Infrastructure\Sulu\Admin\TrashAdmin($a, $b, $c, new RewindableGenerator(function () use ($container) {
            yield 'accounts' => ($container->privates['sulu_contact.account_trash_item_handler'] ?? $container->load('getSuluContact_AccountTrashItemHandlerService'));
            yield 'contacts' => ($container->privates['sulu_contact.contact_trash_item_handler'] ?? $container->load('getSuluContact_ContactTrashItemHandlerService'));
            yield 'media' => ($container->privates['sulu_media.media_trash_item_handler'] ?? $container->load('getSuluMedia_MediaTrashItemHandlerService'));
            yield 'collections' => ($container->privates['sulu_media.collection_trash_item_handler'] ?? $container->load('getSuluMedia_CollectionTrashItemHandlerService'));
            yield 'categories' => ($container->privates['sulu_category.category_trash_item_handler'] ?? $container->load('getSuluCategory_CategoryTrashItemHandlerService'));
            yield 'snippets' => ($container->privates['sulu_snippet.snippet_trash_item_handler'] ?? $container->load('getSuluSnippet_SnippetTrashItemHandlerService'));
            yield 'pages' => ($container->privates['sulu_page.page_trash_item_handler'] ?? $container->load('getSuluPage_PageTrashItemHandlerService'));
            yield 'tags' => ($container->privates['sulu_tag.tag_trash_item_handler'] ?? $container->load('getSuluTag_TagTrashItemHandlerService'));
            yield 'analytics' => ($container->privates['sulu_website.analytics_trash_item_handler'] ?? $container->load('getSuluWebsite_AnalyticsTrashItemHandlerService'));
            yield 'custom_urls' => ($container->privates['sulu_custom_urls.custom_url_trash_item_handler'] ?? $container->load('getSuluCustomUrls_CustomUrlTrashItemHandlerService'));
        }, 10)));
        $instance->addAdmin(new \Sulu\Bundle\SecurityBundle\Admin\SecurityAdmin($a, $b, $d, ($container->services['translator'] ?? $container->getTranslatorService()), $instance, $container->parameters['sulu_admin.resources']));

        return $instance;
    }
}
