<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_LoginFailureListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.login_failure_listener' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\EventListener\AuhenticationFailureListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/EventListener/AuhenticationFailureListener.php';

        return $container->privates['sulu_security.login_failure_listener'] = new \Sulu\Bundle\SecurityBundle\EventListener\AuhenticationFailureListener(($container->services['.container.private.security.password_encoder'] ?? $container->load('get_Container_Private_Security_PasswordEncoderService')), ($container->services['sulu.repository.user'] ?? $container->getSulu_Repository_UserService()));
    }
}
