<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_DoctrineAccessControlProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.doctrine_access_control_provider' shared service.
     *
     * @return \Sulu\Component\Security\Authorization\AccessControl\DoctrineAccessControlProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.doctrine_access_control_provider'] = new \Sulu\Component\Security\Authorization\AccessControl\DoctrineAccessControlProvider(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['sulu.repository.role'] ?? $container->getSulu_Repository_RoleService()), ($container->services['sulu.repository.access_control'] ?? $container->getSulu_Repository_AccessControlService()), ($container->services['sulu_security.mask_converter'] ?? $container->getSuluSecurity_MaskConverterService()));
    }
}
