<?php

namespace ContainerYGMJtmU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_CollectionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.collection_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\CollectionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/friendsofsymfony/rest-bundle/Controller/ControllerTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/RestControllerTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/AbstractRestController.php';
        include_once \dirname(__DIR__, 5).'/vendor/handcraftedinthealps/rest-routing-bundle/Routing/ClassResourceInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Security/SecuredControllerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Security/Authorization/AccessControl/SecuredObjectControllerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php';

        return $container->services['sulu_media.collection_controller'] = new \Sulu\Bundle\MediaBundle\Controller\CollectionController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), ($container->services['sulu_core.list_rest_helper'] ?? $container->load('getSuluCore_ListRestHelperService')), ($container->services['sulu_security.security_checker'] ?? $container->getSuluSecurity_SecurityCheckerService()), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->services['sulu_media.system_collections.manager'] ?? $container->load('getSuluMedia_SystemCollections_ManagerService')), ($container->services['sulu_media.collection_manager'] ?? $container->load('getSuluMedia_CollectionManagerService')), $container->parameters['sulu_media.collection.type.default'], $container->parameters['sulu_security.permissions'], 'Sulu\\Bundle\\MediaBundle\\Entity\\Collection');
    }
}
