<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrinePhpcrService extends App_KernelProdContainer
{
    /*
     * Gets the public 'doctrine_phpcr' shared service.
     *
     * @return \Doctrine\Bundle\PHPCRBundle\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/persistence/src/Persistence/ConnectionRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/persistence/src/Persistence/ManagerRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/doctrine-bridge/ManagerRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/phpcr-bundle/src/ManagerRegistry.php';

        return $container->services['doctrine_phpcr'] = new \Doctrine\Bundle\PHPCRBundle\ManagerRegistry($container, $container->parameters['doctrine_phpcr.sessions'], [], 'default', '', 'Doctrine\\Common\\Proxy\\Proxy');
    }
}
