<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDtlContent_Form_Type_PageService extends App_KernelProdContainer
{
    /*
     * Gets the private 'dtl_content.form.type.page' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Form\Type\PageDocumentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Form/Type/AbstractStructureBehaviorType.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Form/Type/BasePageDocumentType.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Form/Type/PageDocumentType.php';

        return $container->privates['dtl_content.form.type.page'] = new \Sulu\Bundle\PageBundle\Form\Type\PageDocumentType(($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), ($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->privates['sulu_document_manager.metadata_factory'] ?? $container->getSuluDocumentManager_MetadataFactoryService()));
    }
}
