<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'jms_serializer' shared service.
     *
     * @return \JMS\Serializer\Serializer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/SerializerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/ArrayTransformerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Serializer.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/metadata/src/MetadataFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/metadata/src/AdvancedMetadataFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/metadata/src/MetadataFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/metadata/src/Driver/LazyLoadingDriver.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/GraphNavigator/Factory/GraphNavigatorFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/GraphNavigator/Factory/DeserializationGraphNavigatorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Handler/HandlerRegistryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer-bundle/Debug/TraceableHandlerRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Handler/HandlerRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Handler/LazyHandlerRegistry.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Construction/ObjectConstructorInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Construction/UnserializeObjectConstructor.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Accessor/AccessorStrategyInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Expression/CompilableExpressionEvaluatorInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Expression/ExpressionEvaluatorInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Expression/ExpressionEvaluator.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/expression-language/ExpressionLanguage.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer-bundle/ExpressionLanguage/BasicSerializerFunctionsProvider.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/EventDispatcher/EventDispatcherInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/EventDispatcher/EventDispatcher.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/EventDispatcher/LazyEventDispatcher.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer-bundle/Debug/TraceableEventDispatcher.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/GraphNavigator/Factory/SerializationGraphNavigatorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Visitor/Factory/SerializationVisitorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Visitor/Factory/JsonSerializationVisitorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Visitor/Factory/XmlSerializationVisitorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Visitor/Factory/DeserializationVisitorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Visitor/Factory/JsonDeserializationVisitorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Visitor/Factory/XmlDeserializationVisitorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/ContextFactory/SerializationContextFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/ContextFactory/DeserializationContextFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer-bundle/ContextFactory/ConfiguredContextFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Type/ParserInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Type/Parser.php';

        $a = new \Metadata\MetadataFactory(new \Metadata\Driver\LazyLoadingDriver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'metadata_driver' => ['services', 'jms_serializer.metadata_driver', 'getJmsSerializer_MetadataDriverService', true],
        ], [
            'metadata_driver' => '?',
        ]), 'metadata_driver'), 'Metadata\\ClassHierarchyMetadata', false);
        $a->setCache(($container->privates['jms_serializer.metadata.traceable_cache'] ?? $container->load('getJmsSerializer_Metadata_TraceableCacheService')));
        $a->setIncludeInterfaces(false);
        $b = new \JMS\SerializerBundle\Debug\TraceableHandlerRegistry(new \JMS\Serializer\Handler\LazyHandlerRegistry(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sulu_core.rest.datetime_handler' => ['privates', 'sulu_core.rest.datetime_handler', 'getSuluCore_Rest_DatetimeHandlerService', true],
            'jms_serializer.datetime_handler' => ['privates', 'jms_serializer.datetime_handler', 'getJmsSerializer_DatetimeHandlerService', true],
            'jms_serializer.array_collection_handler' => ['privates', 'jms_serializer.array_collection_handler', 'getJmsSerializer_ArrayCollectionHandlerService', true],
            'jms_serializer.iterator_handler' => ['privates', 'jms_serializer.iterator_handler', 'getJmsSerializer_IteratorHandlerService', true],
            'sulu_page.document.serializer.handler.structure' => ['privates', 'sulu_page.document.serializer.handler.structure', 'getSuluPage_Document_Serializer_Handler_StructureService', true],
            'sulu_page.document.serializer.handler.extension_container' => ['privates', 'sulu_page.document.serializer.handler.extension_container', 'getSuluPage_Document_Serializer_Handler_ExtensionContainerService', true],
            'sulu_page.compat.serializer.handler.page_bridge' => ['privates', 'sulu_page.compat.serializer.handler.page_bridge', 'getSuluPage_Compat_Serializer_Handler_PageBridgeService', true],
            'fos_rest.serializer.flatten_exception_handler' => ['privates', 'fos_rest.serializer.flatten_exception_handler', 'getFosRest_Serializer_FlattenExceptionHandlerService', true],
            'jms_serializer.constraint_violation_handler' => ['privates', 'jms_serializer.constraint_violation_handler', 'getJmsSerializer_ConstraintViolationHandlerService', true],
            'sulu_admin.schema_handler' => ['privates', 'sulu_admin.schema_handler', 'getSuluAdmin_SchemaHandlerService', true],
            'sulu_document_manager.serializer.handler.children_collection' => ['privates', 'sulu_document_manager.serializer.handler.children_collection', 'getSuluDocumentManager_Serializer_Handler_ChildrenCollectionService', true],
            'fos_rest.serializer.form_error_handler' => ['privates', 'fos_rest.serializer.form_error_handler', 'getFosRest_Serializer_FormErrorHandlerService', true],
        ], [
            'sulu_core.rest.datetime_handler' => '?',
            'jms_serializer.datetime_handler' => '?',
            'jms_serializer.array_collection_handler' => '?',
            'jms_serializer.iterator_handler' => '?',
            'sulu_page.document.serializer.handler.structure' => '?',
            'sulu_page.document.serializer.handler.extension_container' => '?',
            'sulu_page.compat.serializer.handler.page_bridge' => '?',
            'fos_rest.serializer.flatten_exception_handler' => '?',
            'jms_serializer.constraint_violation_handler' => '?',
            'sulu_admin.schema_handler' => '?',
            'sulu_document_manager.serializer.handler.children_collection' => '?',
            'fos_rest.serializer.form_error_handler' => '?',
        ])));
        $b->registerHandler(2, 'DateTime', 'array', [0 => 'sulu_core.rest.datetime_handler', 1 => 'deserialize']);
        $b->registerHandler(2, 'DateTime', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateTimeFromjson']);
        $b->registerHandler(2, 'DateTime', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateTimeFromxml']);
        $b->registerHandler(2, 'DateTimeImmutable', 'array', [0 => 'sulu_core.rest.datetime_handler', 1 => 'deserialize']);
        $b->registerHandler(2, 'DateTimeImmutable', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateTimeImmutableFromjson']);
        $b->registerHandler(2, 'DateTimeImmutable', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateTimeImmutableFromxml']);
        $b->registerHandler(2, 'ArrayCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'ArrayCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'ArrayCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\Common\\Collections\\ArrayCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\Common\\Collections\\ArrayCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\Common\\Collections\\ArrayCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ORM\\PersistentCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ORM\\PersistentCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ORM\\PersistentCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ODM\\MongoDB\\PersistentCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ODM\\MongoDB\\PersistentCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ODM\\MongoDB\\PersistentCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ODM\\PHPCR\\PersistentCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ODM\\PHPCR\\PersistentCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'Doctrine\\ODM\\PHPCR\\PersistentCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'deserializeCollection']);
        $b->registerHandler(2, 'DateInterval', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateIntervalFromjson']);
        $b->registerHandler(2, 'DateInterval', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateIntervalFromxml']);
        $b->registerHandler(2, 'DateTimeInterface', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateTimeFromJson']);
        $b->registerHandler(2, 'DateTimeInterface', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'deserializeDateTimeFromXml']);
        $b->registerHandler(2, 'Iterator', 'json', [0 => 'jms_serializer.iterator_handler', 1 => 'deserializeIterator']);
        $b->registerHandler(2, 'Iterator', 'xml', [0 => 'jms_serializer.iterator_handler', 1 => 'deserializeIterator']);
        $b->registerHandler(2, 'ArrayIterator', 'json', [0 => 'jms_serializer.iterator_handler', 1 => 'deserializeIterator']);
        $b->registerHandler(2, 'ArrayIterator', 'xml', [0 => 'jms_serializer.iterator_handler', 1 => 'deserializeIterator']);
        $b->registerHandler(2, 'Generator', 'json', [0 => 'jms_serializer.iterator_handler', 1 => 'deserializeGenerator']);
        $b->registerHandler(2, 'Generator', 'xml', [0 => 'jms_serializer.iterator_handler', 1 => 'deserializeGenerator']);
        $b->registerHandler(2, 'Sulu\\Component\\Content\\Document\\Structure\\Structure', 'json', [0 => 'sulu_page.document.serializer.handler.structure', 1 => 'doDeserialize']);
        $b->registerHandler(2, 'Sulu\\Component\\Content\\Document\\Extension\\ExtensionContainer', 'json', [0 => 'sulu_page.document.serializer.handler.extension_container', 1 => 'doDeserialize']);
        $b->registerHandler(2, 'Sulu\\Component\\Content\\Compat\\Structure\\PageBridge', 'json', [0 => 'sulu_page.compat.serializer.handler.page_bridge', 1 => 'doDeserialize']);
        $b->registerHandler(1, 'DateTime', 'array', [0 => 'sulu_core.rest.datetime_handler', 1 => 'serialize']);
        $b->registerHandler(1, 'DateTime', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateTime']);
        $b->registerHandler(1, 'DateTime', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateTime']);
        $b->registerHandler(1, 'DateTimeImmutable', 'array', [0 => 'sulu_core.rest.datetime_handler', 1 => 'serialize']);
        $b->registerHandler(1, 'DateTimeImmutable', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateTimeImmutable']);
        $b->registerHandler(1, 'DateTimeImmutable', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateTimeImmutable']);
        $b->registerHandler(1, 'Symfony\\Component\\ErrorHandler\\Exception\\FlattenException', 'json', [0 => 'fos_rest.serializer.flatten_exception_handler', 1 => 'serializeToJson']);
        $b->registerHandler(1, 'Symfony\\Component\\ErrorHandler\\Exception\\FlattenException', 'xml', [0 => 'fos_rest.serializer.flatten_exception_handler', 1 => 'serializeToXml']);
        $b->registerHandler(1, 'ArrayCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'ArrayCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'ArrayCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\Common\\Collections\\ArrayCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\Common\\Collections\\ArrayCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\Common\\Collections\\ArrayCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ORM\\PersistentCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ORM\\PersistentCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ORM\\PersistentCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ODM\\MongoDB\\PersistentCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ODM\\MongoDB\\PersistentCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ODM\\MongoDB\\PersistentCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ODM\\PHPCR\\PersistentCollection', 'json', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ODM\\PHPCR\\PersistentCollection', 'xml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Doctrine\\ODM\\PHPCR\\PersistentCollection', 'yml', [0 => 'jms_serializer.array_collection_handler', 1 => 'serializeCollection']);
        $b->registerHandler(1, 'Symfony\\Component\\Validator\\ConstraintViolationList', 'xml', [0 => 'jms_serializer.constraint_violation_handler', 1 => 'serializeListToxml']);
        $b->registerHandler(1, 'Symfony\\Component\\Validator\\ConstraintViolationList', 'json', [0 => 'jms_serializer.constraint_violation_handler', 1 => 'serializeListTojson']);
        $b->registerHandler(1, 'Symfony\\Component\\Validator\\ConstraintViolation', 'xml', [0 => 'jms_serializer.constraint_violation_handler', 1 => 'serializeViolationToxml']);
        $b->registerHandler(1, 'Symfony\\Component\\Validator\\ConstraintViolation', 'json', [0 => 'jms_serializer.constraint_violation_handler', 1 => 'serializeViolationTojson']);
        $b->registerHandler(1, 'DateInterval', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateInterval']);
        $b->registerHandler(1, 'DateInterval', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateInterval']);
        $b->registerHandler(1, 'DateTimeInterface', 'json', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateTimeInterface']);
        $b->registerHandler(1, 'DateTimeInterface', 'xml', [0 => 'jms_serializer.datetime_handler', 1 => 'serializeDateTimeInterface']);
        $b->registerHandler(1, 'Iterator', 'json', [0 => 'jms_serializer.iterator_handler', 1 => 'serializeIterable']);
        $b->registerHandler(1, 'Iterator', 'xml', [0 => 'jms_serializer.iterator_handler', 1 => 'serializeIterable']);
        $b->registerHandler(1, 'ArrayIterator', 'json', [0 => 'jms_serializer.iterator_handler', 1 => 'serializeIterable']);
        $b->registerHandler(1, 'ArrayIterator', 'xml', [0 => 'jms_serializer.iterator_handler', 1 => 'serializeIterable']);
        $b->registerHandler(1, 'Generator', 'json', [0 => 'jms_serializer.iterator_handler', 1 => 'serializeIterable']);
        $b->registerHandler(1, 'Generator', 'xml', [0 => 'jms_serializer.iterator_handler', 1 => 'serializeIterable']);
        $b->registerHandler(1, 'Sulu\\Bundle\\AdminBundle\\Metadata\\SchemaMetadata\\SchemaMetadata', 'json', [0 => 'sulu_admin.schema_handler', 1 => 'serializeToJsonSchema']);
        $b->registerHandler(1, 'Sulu\\Component\\Content\\Document\\Structure\\Structure', 'json', [0 => 'sulu_page.document.serializer.handler.structure', 1 => 'doSerialize']);
        $b->registerHandler(1, 'Sulu\\Component\\Content\\Document\\Extension\\ExtensionContainer', 'json', [0 => 'sulu_page.document.serializer.handler.extension_container', 1 => 'doSerialize']);
        $b->registerHandler(1, 'Sulu\\Component\\DocumentManager\\Collection\\ChildrenCollection', 'json', [0 => 'sulu_document_manager.serializer.handler.children_collection', 1 => 'doSerialize']);
        $b->registerHandler(1, 'Symfony\\Component\\Form\\Form', 'xml', [0 => 'fos_rest.serializer.form_error_handler', 1 => 'serializeFormToxml']);
        $b->registerHandler(1, 'Symfony\\Component\\Form\\Form', 'json', [0 => 'fos_rest.serializer.form_error_handler', 1 => 'serializeFormTojson']);
        $b->registerHandler(1, 'Symfony\\Component\\Form\\FormInterface', 'xml', [0 => 'fos_rest.serializer.form_error_handler', 1 => 'serializeFormInterfaceToxml']);
        $b->registerHandler(1, 'Symfony\\Component\\Form\\FormInterface', 'json', [0 => 'fos_rest.serializer.form_error_handler', 1 => 'serializeFormInterfaceTojson']);
        $b->registerHandler(1, 'Symfony\\Component\\Form\\FormError', 'xml', [0 => 'fos_rest.serializer.form_error_handler', 1 => 'serializeFormErrorToxml']);
        $b->registerHandler(1, 'Symfony\\Component\\Form\\FormError', 'json', [0 => 'fos_rest.serializer.form_error_handler', 1 => 'serializeFormErrorTojson']);
        $c = new \Symfony\Component\ExpressionLanguage\ExpressionLanguage();
        $c->registerProvider(new \JMS\SerializerBundle\ExpressionLanguage\BasicSerializerFunctionsProvider());

        $d = new \JMS\Serializer\Expression\ExpressionEvaluator($c, ['container' => $container]);

        $e = new \JMS\Serializer\Accessor\DefaultAccessorStrategy($d);
        $f = new \JMS\SerializerBundle\Debug\TraceableEventDispatcher(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jms_serializer.traceable_runs_listener' => ['privates', 'jms_serializer.traceable_runs_listener', 'getJmsSerializer_TraceableRunsListenerService', true],
            'jms_serializer.doctrine_proxy_subscriber' => ['privates', 'jms_serializer.doctrine_proxy_subscriber', 'getJmsSerializer_DoctrineProxySubscriberService', true],
            'sulu_page.document.serializer.subscriber.structure_behavior' => ['privates', 'sulu_page.document.serializer.subscriber.structure_behavior', 'getSuluPage_Document_Serializer_Subscriber_StructureBehaviorService', true],
            'sulu_page.document.serializer.subscriber.extension_container' => ['privates', 'sulu_page.document.serializer.subscriber.extension_container', 'getSuluPage_Document_Serializer_Subscriber_ExtensionContainerService', true],
            'sulu_document_manager.serializer.subscriber.proxy' => ['services', 'sulu_document_manager.serializer.subscriber.proxy', 'getSuluDocumentManager_Serializer_Subscriber_ProxyService', true],
            'sulu_core.representation_handler' => ['privates', 'sulu_core.representation_handler', 'getSuluCore_RepresentationHandlerService', true],
            'sulu_admin.dropdown_toolbar_action_subscriber' => ['privates', 'sulu_admin.dropdown_toolbar_action_subscriber', 'getSuluAdmin_DropdownToolbarActionSubscriberService', true],
            'sulu_admin.save_with_form_dialog_toolbar_action_subscriber' => ['privates', 'sulu_admin.save_with_form_dialog_toolbar_action_subscriber', 'getSuluAdmin_SaveWithFormDialogToolbarActionSubscriberService', true],
            'sulu_admin.toggler_toolbar_action_subscriber' => ['privates', 'sulu_admin.toggler_toolbar_action_subscriber', 'getSuluAdmin_TogglerToolbarActionSubscriberService', true],
            'sulu_security.serializer.media_permissions' => ['privates', 'sulu_security.serializer.media_permissions', 'getSuluSecurity_Serializer_MediaPermissionsService', true],
            'sulu_security.serializer.handler.secured_entity' => ['privates', 'sulu_security.serializer.handler.secured_entity', 'getSuluSecurity_Serializer_Handler_SecuredEntityService', true],
            'sulu_security.document.serializer.subscriber.security' => ['privates', 'sulu_security.document.serializer.subscriber.security', 'getSuluSecurity_Document_Serializer_Subscriber_SecurityService', true],
            'sulu_page.webspace.serializer.event_subscriber' => ['privates', 'sulu_page.webspace.serializer.event_subscriber', 'getSuluPage_Webspace_Serializer_EventSubscriberService', true],
            'sulu_page.content_repository.event_subscriber' => ['privates', 'sulu_page.content_repository.event_subscriber', 'getSuluPage_ContentRepository_EventSubscriberService', true],
            'sulu_page.teaser.serializer.event_subscriber' => ['privates', 'sulu_page.teaser.serializer.event_subscriber', 'getSuluPage_Teaser_Serializer_EventSubscriberService', true],
            'sulu_page.document.serializer.subscriber.path_behavior' => ['privates', 'sulu_page.document.serializer.subscriber.path_behavior', 'getSuluPage_Document_Serializer_Subscriber_PathBehaviorService', true],
            'sulu_page.document.serializer.subscriber.parent_behavior' => ['privates', 'sulu_page.document.serializer.subscriber.parent_behavior', 'getSuluPage_Document_Serializer_Subscriber_ParentBehaviorService', true],
            'sulu_page.document.serializer.subscriber.locale' => ['privates', 'sulu_page.document.serializer.subscriber.locale', 'getSuluPage_Document_Serializer_Subscriber_LocaleService', true],
            'sulu_page.document.serializer.subscriber.shadow_locale_behavior' => ['privates', 'sulu_page.document.serializer.subscriber.shadow_locale_behavior', 'getSuluPage_Document_Serializer_Subscriber_ShadowLocaleBehaviorService', true],
            'sulu_page.document.serializer.subscriber.redirect_type_behavior' => ['privates', 'sulu_page.document.serializer.subscriber.redirect_type_behavior', 'getSuluPage_Document_Serializer_Subscriber_RedirectTypeBehaviorService', true],
            'sulu_page.document.serializer.subscriber.workflow_stage_behavior' => ['privates', 'sulu_page.document.serializer.subscriber.workflow_stage_behavior', 'getSuluPage_Document_Serializer_Subscriber_WorkflowStageBehaviorService', true],
            'sulu_page.compat.serializer.subscriber.page_bridge' => ['privates', 'sulu_page.compat.serializer.subscriber.page_bridge', 'getSuluPage_Compat_Serializer_Subscriber_PageBridgeService', true],
            'sulu_website.analytics.event_subscriber' => ['privates', 'sulu_website.analytics.event_subscriber', 'getSuluWebsite_Analytics_EventSubscriberService', true],
            'sulu_document_manager.serializer.subscriber.children_behavior' => ['privates', 'sulu_document_manager.serializer.subscriber.children_behavior', 'getSuluDocumentManager_Serializer_Subscriber_ChildrenBehaviorService', true],
            'sulu_hash.event_subscriber.serializer' => ['privates', 'sulu_hash.event_subscriber.serializer', 'getSuluHash_EventSubscriber_SerializerService', true],
            'sulu_custom_urls.serializer.event_subscriber' => ['privates', 'sulu_custom_urls.serializer.event_subscriber', 'getSuluCustomUrls_Serializer_EventSubscriberService', true],
            'sulu_document_manager.serializer.subscriber.document' => ['privates', 'sulu_document_manager.serializer.subscriber.document', 'getSuluDocumentManager_Serializer_Subscriber_DocumentService', true],
        ], [
            'jms_serializer.traceable_runs_listener' => '?',
            'jms_serializer.doctrine_proxy_subscriber' => '?',
            'sulu_page.document.serializer.subscriber.structure_behavior' => '?',
            'sulu_page.document.serializer.subscriber.extension_container' => '?',
            'sulu_document_manager.serializer.subscriber.proxy' => '?',
            'sulu_core.representation_handler' => '?',
            'sulu_admin.dropdown_toolbar_action_subscriber' => '?',
            'sulu_admin.save_with_form_dialog_toolbar_action_subscriber' => '?',
            'sulu_admin.toggler_toolbar_action_subscriber' => '?',
            'sulu_security.serializer.media_permissions' => '?',
            'sulu_security.serializer.handler.secured_entity' => '?',
            'sulu_security.document.serializer.subscriber.security' => '?',
            'sulu_page.webspace.serializer.event_subscriber' => '?',
            'sulu_page.content_repository.event_subscriber' => '?',
            'sulu_page.teaser.serializer.event_subscriber' => '?',
            'sulu_page.document.serializer.subscriber.path_behavior' => '?',
            'sulu_page.document.serializer.subscriber.parent_behavior' => '?',
            'sulu_page.document.serializer.subscriber.locale' => '?',
            'sulu_page.document.serializer.subscriber.shadow_locale_behavior' => '?',
            'sulu_page.document.serializer.subscriber.redirect_type_behavior' => '?',
            'sulu_page.document.serializer.subscriber.workflow_stage_behavior' => '?',
            'sulu_page.compat.serializer.subscriber.page_bridge' => '?',
            'sulu_website.analytics.event_subscriber' => '?',
            'sulu_document_manager.serializer.subscriber.children_behavior' => '?',
            'sulu_hash.event_subscriber.serializer' => '?',
            'sulu_custom_urls.serializer.event_subscriber' => '?',
            'sulu_document_manager.serializer.subscriber.document' => '?',
        ]));
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.traceable_runs_listener', 1 => 'saveRunInfo'], NULL, NULL, NULL);
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerializeTypedProxy'], NULL, NULL, 'Doctrine\\Persistence\\Proxy');
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerializeTypedProxy'], NULL, NULL, 'Doctrine\\Common\\Persistence\\Proxy');
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerialize'], NULL, NULL, 'Doctrine\\ORM\\PersistentCollection');
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerialize'], NULL, NULL, 'Doctrine\\ODM\\MongoDB\\PersistentCollection');
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerialize'], NULL, NULL, 'Doctrine\\ODM\\PHPCR\\PersistentCollection');
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerialize'], NULL, NULL, 'Doctrine\\Persistence\\Proxy');
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerialize'], NULL, NULL, 'Doctrine\\Common\\Persistence\\Proxy');
        $f->addListener('serializer.pre_serialize', [0 => 'jms_serializer.doctrine_proxy_subscriber', 1 => 'onPreSerialize'], NULL, NULL, 'ProxyManager\\Proxy\\LazyLoadingInterface');
        $f->addListener('serializer.pre_serialize', [0 => 'sulu_page.document.serializer.subscriber.structure_behavior', 1 => 'onPreSerialize'], NULL, NULL, NULL);
        $f->addListener('serializer.pre_serialize', [0 => 'sulu_page.document.serializer.subscriber.extension_container', 1 => 'onPreSerialize'], NULL, NULL, NULL);
        $f->addListener('serializer.pre_serialize', [0 => 'sulu_document_manager.serializer.subscriber.proxy', 1 => 'onPreSerialize'], NULL, NULL, NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_core.representation_handler', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_admin.dropdown_toolbar_action_subscriber', 1 => 'onPostSerialize'], 'Sulu\\Bundle\\AdminBundle\\Admin\\View\\DropdownToolbarAction', 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_admin.save_with_form_dialog_toolbar_action_subscriber', 1 => 'onPostSerialize'], 'Sulu\\Bundle\\AdminBundle\\Admin\\View\\SaveWithFormDialogToolbarAction', 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_admin.toggler_toolbar_action_subscriber', 1 => 'onPostSerialize'], 'Sulu\\Bundle\\AdminBundle\\Admin\\View\\TogglerToolbarAction', 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_security.serializer.media_permissions', 1 => 'onPostSerialize'], NULL, NULL, NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_security.serializer.handler.secured_entity', 1 => 'onPostSerialize'], NULL, NULL, NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_security.document.serializer.subscriber.security', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.webspace.serializer.event_subscriber', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.content_repository.event_subscriber', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.teaser.serializer.event_subscriber', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.document.serializer.subscriber.structure_behavior', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.document.serializer.subscriber.path_behavior', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.document.serializer.subscriber.parent_behavior', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.document.serializer.subscriber.locale', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.document.serializer.subscriber.shadow_locale_behavior', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.document.serializer.subscriber.redirect_type_behavior', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.document.serializer.subscriber.workflow_stage_behavior', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_page.compat.serializer.subscriber.page_bridge', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_website.analytics.event_subscriber', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_document_manager.serializer.subscriber.children_behavior', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_hash.event_subscriber.serializer', 1 => 'onPostSerialize'], NULL, NULL, NULL);
        $f->addListener('serializer.post_serialize', [0 => 'sulu_custom_urls.serializer.event_subscriber', 1 => 'onPostSerialize'], NULL, 'json', NULL);
        $f->addListener('serializer.post_deserialize', [0 => 'sulu_document_manager.serializer.subscriber.document', 1 => 'onPostDeserialize'], NULL, NULL, NULL);
        $g = new \JMS\Serializer\Visitor\Factory\JsonSerializationVisitorFactory();
        $g->setOptions(1088);
        $h = new \JMS\Serializer\Visitor\Factory\JsonDeserializationVisitorFactory();
        $h->setOptions(0);

        return $container->services['jms_serializer'] = new \JMS\Serializer\Serializer($a, [2 => new \JMS\Serializer\GraphNavigator\Factory\DeserializationGraphNavigatorFactory($a, $b, new \JMS\Serializer\Construction\UnserializeObjectConstructor(), $e, $f, $d), 1 => new \JMS\Serializer\GraphNavigator\Factory\SerializationGraphNavigatorFactory($a, $b, $e, $f, $d)], ['json' => $g, 'xml' => new \JMS\Serializer\Visitor\Factory\XmlSerializationVisitorFactory()], ['json' => $h, 'xml' => new \JMS\Serializer\Visitor\Factory\XmlDeserializationVisitorFactory()], ($container->services['jms_serializer.serialization_context_factory'] ?? ($container->services['jms_serializer.serialization_context_factory'] = new \JMS\SerializerBundle\ContextFactory\ConfiguredContextFactory())), ($container->services['jms_serializer.deserialization_context_factory'] ?? ($container->services['jms_serializer.deserialization_context_factory'] = new \JMS\SerializerBundle\ContextFactory\ConfiguredContextFactory())), ($container->privates['jms_serializer.type_parser'] ?? ($container->privates['jms_serializer.type_parser'] = new \JMS\Serializer\Type\Parser())));
    }
}
