<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaRedirectControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'sulu_media.media_redirect_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\MediaRedirectController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Controller/MediaRedirectController.php';

        return $container->services['sulu_media.media_redirect_controller'] = new \Sulu\Bundle\MediaBundle\Controller\MediaRedirectController(($container->services['sulu_media.media_manager'] ?? $container->getSuluMedia_MediaManagerService()));
    }
}
