<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_ListBuilder_FieldDescriptorFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'sulu_core.list_builder.field_descriptor_factory' shared service.
     *
     * @return \Sulu\Component\Rest\ListBuilder\Metadata\FieldDescriptorFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactoryInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/ListBuilder/Metadata/ListXmlLoader.php';

        return $container->services['sulu_core.list_builder.field_descriptor_factory'] = new \Sulu\Component\Rest\ListBuilder\Metadata\FieldDescriptorFactory(new \Sulu\Component\Rest\ListBuilder\Metadata\ListXmlLoader(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)))), $container->parameters['sulu_admin.lists.directories'], ($container->targetDir.''.'/sulu/field_descriptor'), false);
    }
}
