<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_Serializer_Handler_SecuredEntityService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_security.serializer.handler.secured_entity' shared service.
     *
     * @return \Sulu\Component\Security\Serializer\Subscriber\SecuredEntitySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/EventDispatcher/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Security/Serializer/Subscriber/SecuredEntitySubscriber.php';

        return $container->privates['sulu_security.serializer.handler.secured_entity'] = new \Sulu\Component\Security\Serializer\Subscriber\SecuredEntitySubscriber(($container->privates['sulu_security.access_control_manager'] ?? $container->getSuluSecurity_AccessControlManagerService()), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
