<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_XmlFormMetadataLoaderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_admin.xml_form_metadata_loader' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\XmlFormMetadataLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataLoaderInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/XmlFormMetadataLoader.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php';

        return $container->privates['sulu_admin.xml_form_metadata_loader'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\XmlFormMetadataLoader(new \Sulu\Bundle\AdminBundle\FormMetadata\FormXmlLoader(($container->privates['sulu_page.structure.properties_xml_parser'] ?? $container->getSuluPage_Structure_PropertiesXmlParserService()), ($container->privates['sulu_page.structure.schema_xml_parser'] ?? ($container->privates['sulu_page.structure.schema_xml_parser'] = new \Sulu\Component\Content\Metadata\Parser\SchemaXmlParser())), $container->parameters['sulu_core.locales'], ($container->privates['sulu_admin.form_metadata.form_metadata_mapper'] ?? $container->load('getSuluAdmin_FormMetadata_FormMetadataMapperService'))), ($container->privates['sulu_admin.field_metadata_validator.chain'] ?? $container->load('getSuluAdmin_FieldMetadataValidator_ChainService')), $container->parameters['sulu_admin.forms.directories'], ($container->targetDir.''.'/sulu/forms'), false);
    }
}
