<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_PathBuilderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_document_manager.path_builder' shared service.
     *
     * @return \Sulu\Component\DocumentManager\PathBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/DocumentManager/PathBuilder.php';

        return $container->privates['sulu_document_manager.path_builder'] = new \Sulu\Component\DocumentManager\PathBuilder(($container->privates['sulu_document_manager.path_segment_registry'] ?? $container->getSuluDocumentManager_PathSegmentRegistryService()));
    }
}
