<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Import_ManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_page.import.manager' shared service.
     *
     * @return \Sulu\Component\Import\Manager\ImportManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Import/Manager/ImportManagerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Import/Manager/ImportManager.php';

        return $container->privates['sulu_page.import.manager'] = new \Sulu\Component\Import\Manager\ImportManager(($container->services['sulu.content.type_manager'] ?? $container->getSulu_Content_TypeManagerService()));
    }
}
