<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_ManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'sulu_custom_urls.manager' shared service.
     *
     * @return \Sulu\Component\CustomUrl\Manager\CustomUrlManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/CustomUrl/Manager/CustomUrlManagerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/CustomUrl/Repository/CustomUrlRepository.php';

        return $container->services['sulu_custom_urls.manager'] = new \Sulu\Component\CustomUrl\Manager\CustomUrlManager(($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['sulu_document_manager.document_inspector'] ?? $container->getSuluDocumentManager_DocumentInspectorService()), new \Sulu\Component\CustomUrl\Repository\CustomUrlRepository(($container->services['sulu.phpcr.session'] ?? $container->getSulu_Phpcr_SessionService()), ($container->services['sulu_page.content_repository'] ?? $container->getSuluPage_ContentRepositoryService()), ($container->privates['sulu_custom_urls.domain_generator'] ?? $container->load('getSuluCustomUrls_DomainGeneratorService')), ($container->services['sulu_security.user_manager'] ?? $container->load('getSuluSecurity_UserManagerService'))), ($container->privates['sulu_document_manager.metadata_factory'] ?? $container->getSuluDocumentManager_MetadataFactoryService()), ($container->privates['sulu_document_manager.path_builder'] ?? $container->load('getSuluDocumentManager_PathBuilderService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? $container->getSuluCore_Webspace_WebspaceManagerService()), 'prod', ($container->privates['sulu_document_manager.document_domain_event_collector'] ?? $container->load('getSuluDocumentManager_DocumentDomainEventCollectorService')));
    }
}
