<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_ContactTitleRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_contact.contact_title_repository' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Entity\ContactTitleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Entity/ContactTitleRepository.php';

        return $container->privates['sulu_contact.contact_title_repository'] = ($container->services['doctrine'] ?? $container->load('getDoctrineService'))->getRepository('SuluContactBundle:ContactTitle');
    }
}
