<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_SmartContentItemControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'sulu_page.smart_content_item_controller' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Controller\SmartContentItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/friendsofsymfony/rest-bundle/Controller/ControllerTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/RestControllerTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/AbstractRestController.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Controller/SmartContentItemController.php';

        return $container->services['sulu_page.smart_content_item_controller'] = new \Sulu\Bundle\PageBundle\Controller\SmartContentItemController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_tag.tag_manager'] ?? $container->getSuluTag_TagManagerService()), ($container->services['sulu_page.smart_content.data_provider_pool'] ?? $container->load('getSuluPage_SmartContent_DataProviderPoolService')), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
