<?php

namespace Container59KXm3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Cache_MemoizeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_core.cache.memoize' shared service.
     *
     * @return \Sulu\Component\Cache\Memoize
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Cache/MemoizeInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Cache/Memoize.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ArrayCache.php';

        return $container->privates['sulu_core.cache.memoize'] = new \Sulu\Component\Cache\Memoize(new \Doctrine\Common\Cache\ArrayCache(), 1);
    }
}
