<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container59KXm3P\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container59KXm3P/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container59KXm3P.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container59KXm3P\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container59KXm3P\App_KernelProdContainer([
    'container.build_hash' => '59KXm3P',
    'container.build_id' => '87dd6eef',
    'container.build_time' => 1651322119,
], __DIR__.\DIRECTORY_SEPARATOR.'Container59KXm3P');
