<?php

namespace ContainerLNhbh91;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Rest_DatetimeHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.rest.datetime_handler' shared service.
     *
     * @return \Sulu\Component\Rest\Handler\DateHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/jms/serializer/src/Handler/SubscribingHandlerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/Handler/DateHandler.php';

        return $container->privates['sulu_core.rest.datetime_handler'] = new \Sulu\Component\Rest\Handler\DateHandler();
    }
}
