<?php

namespace ContainerLNhbh91;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_DownloadLanguageCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_admin.download_language_command' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Command\DownloadLanguageCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Command/DownloadLanguageCommand.php';

        $container->privates['sulu_admin.download_language_command'] = $instance = new \Sulu\Bundle\AdminBundle\Command\DownloadLanguageCommand(\Symfony\Component\HttpClient\HttpClient::create(), ($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), \dirname(__DIR__, 5), $container->parameters['sulu_core.locales']);

        $instance->setName('sulu:admin:download-language');

        return $instance;
    }
}
