<?php

namespace ContainerLNhbh91;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Command_FixturesLoadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.command.fixtures_load' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Command\FixturesLoadCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/DataFixtures/DocumentExecutor.php';

        $container->privates['sulu_document_manager.command.fixtures_load'] = $instance = new \Sulu\Bundle\DocumentManagerBundle\Command\FixturesLoadCommand(new \Sulu\Bundle\DocumentManagerBundle\DataFixtures\DocumentExecutor(($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['sulu_document_manager.initializer'] ?? $container->load('getSuluDocumentManager_InitializerService'))), new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0));

        $instance->setName('sulu:document:fixtures:load');

        return $instance;
    }
}
