<?php

namespace ContainerLNhbh91;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSearch_Controller_WebsiteSearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_search.controller.website_search' shared service.
     *
     * @return \Sulu\Bundle\SearchBundle\Controller\WebsiteSearchController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php';

        return $container->services['sulu_search.controller.website_search'] = new \Sulu\Bundle\SearchBundle\Controller\WebsiteSearchController(($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService')), ($container->services['sulu_core.webspace.request_analyzer'] ?? $container->getSuluCore_Webspace_RequestAnalyzerService()), ($container->services['sulu_website.resolver.parameter'] ?? $container->load('getSuluWebsite_Resolver_ParameterService')), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), $container->parameters['sulu_search.website.indexes'], ($container->services['sulu_website.resolver.template_attribute'] ?? $container->load('getSuluWebsite_Resolver_TemplateAttributeService')));
    }
}
