<?php

namespace Proxies\__CG__\Sulu\Bundle\ActivityBundle\Domain\Model;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activity extends \Sulu\Bundle\ActivityBundle\Domain\Model\Activity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'id', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'type', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'context', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'payload', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'timestamp', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'batch', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'user', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceKey', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceId', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceLocale', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceWebspaceKey', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceTitle', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceTitleLocale', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceSecurityContext', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceSecurityObjectType', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceSecurityObjectId'];
        }

        return ['__isInitialized__', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'id', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'type', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'context', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'payload', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'timestamp', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'batch', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'user', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceKey', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceId', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceLocale', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceWebspaceKey', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceTitle', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceTitleLocale', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceSecurityContext', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceSecurityObjectType', '' . "\0" . 'Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity' . "\0" . 'resourceSecurityObjectId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getType(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getContext(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContext', []);

        return parent::getContext();
    }

    /**
     * {@inheritDoc}
     */
    public function setContext(array $context): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContext', [$context]);

        return parent::setContext($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayload(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayload', []);

        return parent::getPayload();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayload(?array $payload): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayload', [$payload]);

        return parent::setPayload($payload);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp(): \DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp(\DateTimeImmutable $timestamp): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', [$timestamp]);

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getBatch(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBatch', []);

        return parent::getBatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setBatch(?string $batch): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBatch', [$batch]);

        return parent::setBatch($batch);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\Sulu\Component\Security\Authentication\UserInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\Sulu\Component\Security\Authentication\UserInterface $user): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceKey(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceKey', []);

        return parent::getResourceKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceKey(string $resourceKey): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceKey', [$resourceKey]);

        return parent::setResourceKey($resourceKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceId', []);

        return parent::getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceId(string $resourceId): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceId', [$resourceId]);

        return parent::setResourceId($resourceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceLocale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceLocale', []);

        return parent::getResourceLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceLocale(?string $resourceLocale): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceLocale', [$resourceLocale]);

        return parent::setResourceLocale($resourceLocale);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceWebspaceKey(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceWebspaceKey', []);

        return parent::getResourceWebspaceKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceWebspaceKey(?string $resourceWebspaceKey): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceWebspaceKey', [$resourceWebspaceKey]);

        return parent::setResourceWebspaceKey($resourceWebspaceKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceTitle', []);

        return parent::getResourceTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceTitle(?string $resourceTitle): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceTitle', [$resourceTitle]);

        return parent::setResourceTitle($resourceTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceTitleLocale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceTitleLocale', []);

        return parent::getResourceTitleLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceTitleLocale(?string $resourceTitleLocale): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceTitleLocale', [$resourceTitleLocale]);

        return parent::setResourceTitleLocale($resourceTitleLocale);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceSecurityContext(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceSecurityContext', []);

        return parent::getResourceSecurityContext();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceSecurityContext(?string $resourceSecurityContext): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceSecurityContext', [$resourceSecurityContext]);

        return parent::setResourceSecurityContext($resourceSecurityContext);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceSecurityObjectType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceSecurityObjectType', []);

        return parent::getResourceSecurityObjectType();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceSecurityObjectType(?string $resourceSecurityObjectType): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceSecurityObjectType', [$resourceSecurityObjectType]);

        return parent::setResourceSecurityObjectType($resourceSecurityObjectType);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceSecurityObjectId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceSecurityObjectId', []);

        return parent::getResourceSecurityObjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceSecurityObjectId(?string $resourceSecurityObjectId): \Sulu\Bundle\ActivityBundle\Domain\Model\ActivityInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceSecurityObjectId', [$resourceSecurityObjectId]);

        return parent::setResourceSecurityObjectId($resourceSecurityObjectId);
    }

}
