<?php

namespace ContainerUx2i24J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssets_PackageSuluAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'assets._package_sulu_admin' shared service.
     *
     * @return \Symfony\Component\Asset\PathPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['assets._package_sulu_admin'] = new \Symfony\Component\Asset\PathPackage('', new \Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy((\dirname(__DIR__, 5).'/public/build/admin/manifest.json'), ($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), false), ($container->privates['assets.context'] ?? $container->getAssets_ContextService()));
    }
}
