<?php

namespace ContainerUx2i24J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_Events_DeindexListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_search.events.deindex_listener' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\EventListener\DeindexListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/EventListener/DeindexListener.php';

        return $container->privates['massive_search.events.deindex_listener'] = new \Massive\Bundle\SearchBundle\Search\EventListener\DeindexListener(($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService')));
    }
}
