<?php

namespace ContainerUx2i24J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_Block_SegmentVisitorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu.content.type.block.segment_visitor' shared service.
     *
     * @return \Sulu\Component\Content\Types\Block\SegmentBlockVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Content/Types/Block/BlockVisitorInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Content/Types/Block/SegmentBlockVisitor.php';

        return $container->privates['sulu.content.type.block.segment_visitor'] = new \Sulu\Component\Content\Types\Block\SegmentBlockVisitor(($container->services['sulu_core.webspace.request_analyzer'] ?? $container->getSuluCore_Webspace_RequestAnalyzerService()));
    }
}
