<?php

namespace ContainerUx2i24J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStructureInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HspzwsT.Sulu\Component\Content\Compat\StructureInterface' shared service.
     *
     * @return \Sulu\Component\Content\Compat\StructureInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HspzwsT": it references interface "Sulu\\Component\\Content\\Compat\\StructureInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
