<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_ObjectToDocumentConverterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'massive_search.object_to_document_converter' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/ObjectToDocumentConverter.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/Converter/ConverterManagerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/Converter/ConverterManager.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/Converter/ConverterInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/Converter/Types/DateConverter.php';
        include_once \dirname(__DIR__, 5).'/vendor/massive/search-bundle/Search/Converter/Types/JsonConverter.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SearchBundle/Search/Converter/StructureConverter.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/Search/Converter/CategoryConverter.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/TagBundle/Search/TagsConverter.php';

        $a = new \Massive\Bundle\SearchBundle\Search\Converter\ConverterManager();

        $container->privates['massive_search.object_to_document_converter'] = $instance = new \Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter(($container->privates['sulu_search.search.factory'] ?? ($container->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())), ($container->privates['massive_search.metadata.field_evaluator'] ?? $container->load('getMassiveSearch_Metadata_FieldEvaluatorService')), $a);
        $b = ($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService'));
        $c = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        $a->addConverter('date', new \Massive\Bundle\SearchBundle\Search\Converter\Types\DateConverter());
        $a->addConverter('json', new \Massive\Bundle\SearchBundle\Search\Converter\Types\JsonConverter());
        $a->addConverter('structure', new \Sulu\Bundle\SearchBundle\Search\Converter\StructureConverter(($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), $b, $instance, $c));
        $a->addConverter('category', new \Sulu\Bundle\CategoryBundle\Search\Converter\CategoryConverter(($container->services['sulu_category.category_manager'] ?? $container->getSuluCategory_CategoryManagerService()), $b, $instance, $c));
        $a->addConverter('tags', new \Sulu\Bundle\TagBundle\Search\TagsConverter(($container->services['sulu_tag.tag_manager'] ?? $container->getSuluTag_TagManagerService())));

        return $instance;
    }
}
