<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigratorMigrateCommandService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.Doctrine\Bundle\PHPCRBundle\Command\MigratorMigrateCommand' shared service.
     *
     * @return \Doctrine\Bundle\PHPCRBundle\Command\MigratorMigrateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/phpcr-bundle/src/Command/MigratorMigrateCommand.php';

        $container->services['console.command.public_alias.Doctrine\\Bundle\\PHPCRBundle\\Command\\MigratorMigrateCommand'] = $instance = new \Doctrine\Bundle\PHPCRBundle\Command\MigratorMigrateCommand();

        $instance->setContainer($container);

        return $instance;
    }
}
