<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Command_ImportService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_snippet.command.import' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Command\SnippetImportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/Command/SnippetImportCommand.php';

        $container->privates['sulu_snippet.command.import'] = $instance = new \Sulu\Bundle\SnippetBundle\Command\SnippetImportCommand(($container->services['sulu_snippet.import.snippet'] ?? $container->load('getSuluSnippet_Import_SnippetService')), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        $instance->setName('sulu:snippet:import');

        return $instance;
    }
}
