<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_FormatOptionsManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'sulu_media.format_options_manager' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\FormatOptions\FormatOptionsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManagerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        return $container->services['sulu_media.format_options_manager'] = new \Sulu\Bundle\MediaBundle\Media\FormatOptions\FormatOptionsManager($a, $a->getRepository('SuluMediaBundle:FormatOptions'), ($container->services['sulu_media.media_manager'] ?? $container->getSuluMedia_MediaManagerService()), ($container->services['sulu_media.format_manager'] ?? $container->getSuluMedia_FormatManagerService()), ($container->privates['sulu_activity.domain_event_collector'] ?? $container->getSuluActivity_DomainEventCollectorService()), $container->parameters['sulu_media.image.formats']);
    }
}
