<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Persistence_EventSubscriber_Orm_UserBlameService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu.persistence.event_subscriber.orm.user_blame' shared service.
     *
     * @return \Sulu\Component\Persistence\EventSubscriber\ORM\UserBlameSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php';

        return $container->privates['sulu.persistence.event_subscriber.orm.user_blame'] = new \Sulu\Component\Persistence\EventSubscriber\ORM\UserBlameSubscriber(($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
