<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_EventSubscriber_InvalidationService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_custom_urls.event_subscriber.invalidation' shared service.
     *
     * @return \Sulu\Component\CustomUrl\Document\Subscriber\InvalidationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Component/CustomUrl/Document/Subscriber/InvalidationSubscriber.php';

        return $container->privates['sulu_custom_urls.event_subscriber.invalidation'] = new \Sulu\Component\CustomUrl\Document\Subscriber\InvalidationSubscriber(($container->services['sulu_custom_urls.manager'] ?? $container->getSuluCustomUrls_ManagerService()), ($container->services['sulu_document_manager.document_inspector'] ?? $container->getSuluDocumentManager_DocumentInspectorService()), ($container->privates['sulu_http_cache.cache_manager'] ?? $container->load('getSuluHttpCache_CacheManagerService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
