<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Search_Subscriber_MediaService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_media.search.subscriber.media' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Search\Subscriber\MediaSearchSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Search/Subscriber/MediaSearchSubscriber.php';

        return $container->privates['sulu_media.search.subscriber.media'] = new \Sulu\Bundle\MediaBundle\Search\Subscriber\MediaSearchSubscriber(($container->services['sulu_media.media_manager'] ?? $container->getSuluMedia_MediaManagerService()), ($container->privates['sulu_search.search.factory'] ?? ($container->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())), $container->parameters['sulu_media.format_manager.mime_types'], 'sulu-100x100', ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
