<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_DownloadBuildCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_admin.download_build_command' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Command\DownloadBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php';

        $container->privates['sulu_admin.download_build_command'] = $instance = new \Sulu\Bundle\AdminBundle\Command\DownloadBuildCommand();

        $instance->setName('sulu:admin:download-build');

        return $instance;
    }
}
