<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_CollectionManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'sulu_media.collection_manager' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Collection\Manager\CollectionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManagerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php';

        return $container->services['sulu_media.collection_manager'] = new \Sulu\Bundle\MediaBundle\Collection\Manager\CollectionManager(($container->services['sulu_media.collection_repository'] ?? $container->getSuluMedia_CollectionRepositoryService()), ($container->services['sulu.repository.media'] ?? $container->getSulu_Repository_MediaService()), ($container->services['sulu_media.format_manager'] ?? $container->getSuluMedia_FormatManagerService()), ($container->services['sulu.repository.user'] ?? $container->getSulu_Repository_UserService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['sulu_activity.domain_event_collector'] ?? $container->getSuluActivity_DomainEventCollectorService()), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), ($container->privates['sulu_trash.trash_manager'] ?? $container->getSuluTrash_TrashManagerService()), 'sulu-50x50', $container->parameters['sulu_security.permissions']);
    }
}
