<?php

namespace ContainerQpTHIsG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_DocumentManager_EventSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'sulu_snippet.document_manager.event_subscriber' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\EventListener\DomainEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/EventListener/DomainEventSubscriber.php';

        return $container->privates['sulu_snippet.document_manager.event_subscriber'] = new \Sulu\Bundle\SnippetBundle\EventListener\DomainEventSubscriber(($container->privates['sulu_document_manager.document_domain_event_collector'] ?? $container->getSuluDocumentManager_DocumentDomainEventCollectorService()), ($container->services['sulu_document_manager.document_manager'] ?? $container->getSuluDocumentManager_DocumentManagerService()), ($container->services['sulu_document_manager.property_encoder'] ?? $container->getSuluDocumentManager_PropertyEncoderService()));
    }
}
